import { useLocation } from "react-router-dom";
import { Helmet } from "react-helmet";
import { CheckCircle, Phone, Calendar, ArrowRight, Clock, Video, Download, Globe, Mail, IndianRupee, Target, TrendingDown } from "lucide-react";
import { Footer } from "@/components/landing/Footer";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ClientLogosSection } from "@/components/landing/ClientLogosSection";
import { TestimonialSection } from "@/components/landing/TestimonialSection";
import { Navbar } from "@/components/Navbar";
import { useFunnelData } from "@/hooks/useFunnelData";
import { Badge } from "@/components/ui/badge";

const ThankYou = () => {
  const location = useLocation();
  const { leadData: funnelLeadData, auditData: funnelAuditData, competitorData: funnelCompetitorData } = useFunnelData();
  
  const { 
    name, email, phone, source, bookingDate, startTime, endTime, meetingLink,
    leadData: stateLeadData, auditData: stateAuditData, competitorData: stateCompetitorData 
  } = location.state || {};

  // Use state data first, then fall back to funnel storage
  const leadData = stateLeadData || funnelLeadData;
  const auditData = stateAuditData || funnelAuditData;
  const competitorData = stateCompetitorData || funnelCompetitorData;

  const isBookingConfirmation = source === "booking_calendar" || bookingDate;

  const formatBookingDate = (dateStr: string) => {
    if (!dateStr) return null;
    try {
      const date = new Date(dateStr);
      if (isNaN(date.getTime())) return null;
      return date.toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
    } catch { return null; }
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(amount);
  };

  const handleDownloadReport = () => {
    const reportContent = `
AI SEO AUDIT REPORT
Generated by The Super 30
========================

WEBSITE ANALYZED
${leadData?.website_url || 'N/A'}

CONTACT INFORMATION
Email: ${email || leadData?.email || 'N/A'}
Phone: ${phone || leadData?.phone || 'N/A'}

AUDIT SCORES
- SEO Score: ${auditData?.seo_score || 'N/A'}%
- AI Visibility: ${auditData?.ai_visibility_score || 'N/A'}%
- Performance: ${auditData?.performance_score || 'N/A'}%
- Accessibility: ${auditData?.accessibility_score || 'N/A'}%
- Technical Issues: ${auditData?.technical_issues || 0}

${competitorData ? `
COMPETITOR ANALYSIS
Business Niche: ${competitorData.business_niche}
Industry: ${competitorData.industry_category}
Missed Opportunity Score: ${competitorData.missed_opportunity_score}%
Estimated Monthly Loss: ${formatCurrency(competitorData.estimated_monthly_loss.amount)}

TOP COMPETITORS:
${competitorData.competitors.map((c: any, i: number) => `${i + 1}. ${c.name} (${c.domain}) - Strength: ${c.estimated_strength}%`).join('\n')}

AI RECOMMENDATIONS:
${competitorData.recommendations.map((r: string, i: number) => `${i + 1}. ${r}`).join('\n')}
` : ''}

BOOKING DETAILS
${bookingDate ? `Date: ${formatBookingDate(bookingDate)}` : 'Not scheduled yet'}
${startTime ? `Time: ${startTime}${endTime ? ` - ${endTime}` : ''}` : ''}
${meetingLink ? `Meeting Link: ${meetingLink}` : ''}

---
For questions, contact: thesuper30.ai@gmail.com
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `seo-audit-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <Helmet>
        <title>Thank You | The Super 30</title>
        <meta name="description" content="Thank you for reaching out. We'll be in touch shortly." />
      </Helmet>

      <Navbar />
      <main className="min-h-screen bg-background">
        <section className="relative bg-gradient-to-br from-green-50 via-background to-orange-50/30 py-24 lg:py-32 overflow-hidden">
          <div className="absolute inset-0 bg-[linear-gradient(to_right,hsl(var(--border))_1px,transparent_1px),linear-gradient(to_bottom,hsl(var(--border))_1px,transparent_1px)] bg-[size:4rem_4rem] opacity-20" />
          
          <div className="container relative mx-auto px-4">
            <div className="max-w-4xl mx-auto">
              <div className="text-center mb-8">
                <div className="w-20 h-20 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6 animate-scale-in">
                  <CheckCircle className="w-10 h-10 text-green-500" />
                </div>
                <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-4">
                  {isBookingConfirmation ? "Booking Confirmed!" : `Thank You${name ? `, ${name}` : ''}!`}
                </h1>
                <p className="text-lg text-muted-foreground">
                  {isBookingConfirmation ? "Your strategy call has been scheduled. Check your email for the calendar invite." : "Your request has been received."}
                </p>
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                {/* Booking Details */}
                {isBookingConfirmation && (bookingDate || startTime) && (
                  <Card className="bg-green-50 border-green-200">
                    <CardHeader className="pb-3">
                      <CardTitle className="flex items-center gap-2 text-green-800">
                        <Calendar className="w-5 h-5" />
                        Meeting Details
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-3 text-green-700">
                      {bookingDate && (
                        <p className="flex items-center gap-2">
                          <Calendar className="w-4 h-4" />
                          <span><strong>Date:</strong> {formatBookingDate(bookingDate) || 'Check your email'}</span>
                        </p>
                      )}
                      {startTime && (
                        <p className="flex items-center gap-2">
                          <Clock className="w-4 h-4" />
                          <span><strong>Time:</strong> {startTime}{endTime ? ` - ${endTime}` : ''}</span>
                        </p>
                      )}
                      {meetingLink && (
                        <a href={meetingLink} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-orange-600 hover:text-orange-700 font-medium">
                          <Video className="w-4 h-4" />
                          Join Meeting Link
                        </a>
                      )}
                    </CardContent>
                  </Card>
                )}

                {/* Contact Info */}
                <Card className="border-border">
                  <CardHeader className="pb-3">
                    <CardTitle className="flex items-center gap-2">
                      <Mail className="w-5 h-5 text-blue-500" />
                      Your Information
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-2 text-sm">
                    {leadData?.website_url && (
                      <p className="flex items-center gap-2"><Globe className="w-4 h-4 text-muted-foreground" />{leadData.website_url}</p>
                    )}
                    {(email || leadData?.email) && (
                      <p className="flex items-center gap-2"><Mail className="w-4 h-4 text-muted-foreground" />{email || leadData.email}</p>
                    )}
                    {(phone || leadData?.phone) && (
                      <p className="flex items-center gap-2"><Phone className="w-4 h-4 text-muted-foreground" />{phone || leadData.phone}</p>
                    )}
                  </CardContent>
                </Card>

                {/* Audit Summary */}
                {auditData && (
                  <Card className="border-orange-200 bg-orange-50/50">
                    <CardHeader className="pb-3">
                      <CardTitle className="flex items-center gap-2 text-orange-800">
                        <Target className="w-5 h-5" />
                        Audit Summary
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="grid grid-cols-2 gap-3 text-sm">
                        <div className="bg-white rounded-lg p-3 text-center">
                          <p className="text-muted-foreground text-xs">AI Visibility</p>
                          <p className="text-2xl font-bold text-orange-600">{auditData.ai_visibility_score}%</p>
                        </div>
                        <div className="bg-white rounded-lg p-3 text-center">
                          <p className="text-muted-foreground text-xs">SEO Score</p>
                          <p className="text-2xl font-bold text-blue-600">{auditData.seo_score}%</p>
                        </div>
                        <div className="bg-white rounded-lg p-3 text-center">
                          <p className="text-muted-foreground text-xs">Performance</p>
                          <p className="text-2xl font-bold text-green-600">{auditData.performance_score}%</p>
                        </div>
                        <div className="bg-white rounded-lg p-3 text-center">
                          <p className="text-muted-foreground text-xs">Issues Found</p>
                          <p className="text-2xl font-bold text-red-600">{auditData.technical_issues}</p>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                )}

                {/* Competitor Analysis */}
                {competitorData && (
                  <Card className="border-purple-200 bg-purple-50/50">
                    <CardHeader className="pb-3">
                      <CardTitle className="flex items-center gap-2 text-purple-800">
                        <TrendingDown className="w-5 h-5" />
                        Competitor Insights
                        <Badge className="bg-purple-100 text-purple-700 text-xs">AI</Badge>
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-3">
                      <div className="bg-white rounded-lg p-3">
                        <p className="text-xs text-muted-foreground">Business Niche</p>
                        <p className="font-semibold text-foreground">{competitorData.business_niche}</p>
                      </div>
                      <div className="bg-red-100 rounded-lg p-3 text-center">
                        <p className="text-xs text-red-700">Estimated Monthly Loss</p>
                        <p className="text-2xl font-bold text-red-600 flex items-center justify-center gap-1">
                          <IndianRupee className="w-5 h-5" />
                          {formatCurrency(competitorData.estimated_monthly_loss.amount)}
                        </p>
                      </div>
                      <div className="bg-white rounded-lg p-3">
                        <p className="text-xs text-muted-foreground mb-2">Top Competitors</p>
                        {competitorData.competitors.slice(0, 3).map((c: any, i: number) => (
                          <p key={i} className="text-sm">{c.name} <span className="text-muted-foreground">({c.estimated_strength}%)</span></p>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                )}
              </div>

              {/* Download & CTA */}
              <div className="mt-8 text-center space-y-4">
                {(auditData || competitorData) && (
                  <Button onClick={handleDownloadReport} variant="outline" className="gap-2">
                    <Download className="w-4 h-4" />
                    Download Full Report
                  </Button>
                )}
                
                <div className="bg-gradient-to-r from-orange-500 to-orange-600 rounded-2xl p-6 text-white">
                  <p className="text-orange-100 mb-2">Can't wait? Talk to us now!</p>
                  <a href="tel:+917353252526" className="inline-flex items-center gap-2 text-2xl font-bold hover:underline">
                    <Phone className="w-6 h-6" />
                    +91 73532 52526
                  </a>
                </div>

                <Button asChild className="bg-gradient-to-r from-orange-500 to-orange-600 hover:from-orange-600 hover:to-orange-700">
                  <a href="/">Explore Our Services <ArrowRight className="w-4 h-4 ml-2" /></a>
                </Button>
              </div>
            </div>
          </div>
        </section>

        <ClientLogosSection />
        <TestimonialSection />
        <Footer />
      </main>
    </>
  );
};

export default ThankYou;
